-- Integrantes | RM
-- Augusto Barcelos Barros | 98078
-- Gabriel Souza de Queiroz | 98570

DROP TABLE T_CKP_CATEGORIA CASCADE CONSTRAINTS;

DROP TABLE T_CKP_LIVRO CASCADE CONSTRAINTS;

DROP TABLE T_CKP_AUTOR CASCADE CONSTRAINTS;

DROP TABLE T_CKP_AUTOR_LIVRO CASCADE CONSTRAINTS;
